#pragma once

typedef enum
{
    DRIVER_OK = 0,
    DRIVER_NOT_INITIALIZED,
    DRIVER_INVALID_ARGUMENT,
    DRIVER_NOT_READY,
    DRIVER_TIMEOUT,
    DRIVER_COMMUNICATION_ERROR,
    DRIVER_INVALID_DATA,
    DRIVER_INTERNAL_ERROR
} DriverStatus;
